### ISSUE TITLE
indexing using GPU

### ISSUE THREAD

**Issue by xiaodaigh** [Evovest/EvoTrees.jl#106]
I took the code from the README. If you use GPU then it doesn't work after is disallow indexing.

```
using EvoTrees
using EvoTrees: sigmoid, logit

# prepare a dataset
features = rand(10000*20) .* 20 .- 10
X = reshape(features, (10000, 20))
Y = sin.(features) .* 0.5 .+ 0.5
Y = logit(Y) + randn(size(Y))
Y = sigmoid(Y)
i = collect(1:size(X, 1))

# train-eval split
i_sample = sample(i, size(i, 1), replace = false)
train_size = 0.8
i_train = i_sample[1:floor(Int, train_size * size(i, 1))]
i_eval = i_sample[floor(Int, train_size * size(i, 1))+1:end]

X_train, X_eval = X[i_train, :], X[i_eval, :]
Y_train, Y_eval = Y[i_train], Y[i_eval]

params1 = EvoTreeRegressor(
    loss=:linear, metric=:mse,
    nrounds=100, nbins = 100,
    λ = 0.5, γ=0.1, η=0.1,
    max_depth = 6, min_weight = 1.0,
    rowsample=0.5, colsample=1.0, device="gpu")

using CUDA
CUDA.allowscalar(false)
@time model = fit_evotree(params1, X_train, Y_train, X_eval = X_eval, Y_eval = Y_eval, print_every_n = 25)
```

**Comment by jeremiedb** [comment]
Thanks for reporting. 
I noticed the warning about the scalar operation on GPU, however it isn't tied to particular performance issue AFAIK. 
Is there a perticular need on your end for having the algorithm to run when scalar operations are not allowed?

**Comment by xiaodaigh** [comment]
Ok. Not sure, but I ran the algorithm on the base dataset [here](https://www.kaggle.com/c/home-credit-default-risk) (by base I mean just used training without merging on any fields).

The GPU implementation was slower than the CPU one. 

Is there a benchmark script?

**Comment by jeremiedb** [comment]
What are the dimensions of the training data (observations, number of features)?

In the README, you can see some benchmarks of CPU vs GPU. Roughly, the GPU starts outperforming CPU on the 500K observations X 100 features (with 0.5 row and col subsample). Benchmarks were obtained with this [script](https://github.com/Evovest/EvoTrees.jl/blob/master/experiments/benchmarks_v2.jl).
