### ISSUE TITLE
Missing values (or NaN) compatibility

### ISSUE THREAD

**Issue by nuclear718** [Evovest/EvoTrees.jl#117]
How to implement EvoTrees model to handle data with missing values? Have any solution can make EvoTrees compatible with missing values(or NaN) like XGBoost model?

**Comment by jeremiedb** [comment]
Thanks for the enquiry!
There's no explicit method for handling missing/NaN values. The approach I've been actually using, even with other implementations like XGBoost and in ML contest context, is to handle those in the data preprocessing stage. Typically by inputing missing with mean/median values, and optionally by adding dummy flag binary variable. 
Let me me know if you'd see another approach worth exploring.

**Comment by nuclear718** [comment]
Thanks for your reply!

The XGBoost can handle missing values! My project is setup XGBoost model to predict stock price and many missing values are included in my training dataset. The XGBoost model work well everyday. (I did not replace the missing values by any pre-processing work, I just keep it "Missing"...)
I am trying do similar work by EvoTrees.jl and it works but missing values can not be accepted. 

May be I use the XGBoost in different algorithm not histogram based?.

(In the XGBoost.jl github pages, the one of the features: ""Sparse feature format, **it allows easy handling of missing values**, and improve computation efficiency."")
