### ISSUE TITLE
Inconsistencies in input scitype declarations and recently added document strings for MLJ API

### ISSUE THREAD

**Issue by ablaom** [Evovest/EvoTrees.jl#159]
In preparing PR #158 I discovered that the new document strings for each each include this section:

---

## Training model
In MLJ or MLJBase, bind an instance `model` to data with
    `mach = machine(model, X, y)` where
- `X`: any table of input features (eg, a `DataFrame`) whose columns
  each have one of the following element scitypes: `Continuous`,
  `Count`, or `<:OrderedFactor`; check column scitypes with `schema(X)`

---

However, this is at odds with the `input_scitype` declarations which allows tables *and* vectors, but columns must all be `Continuous`. 

My guess is that it is the requirement in the doc-string actually works and it is just the `input_scitype` declarations that need updating. @jeremiedb Can you confirm?

**Comment by jeremiedb** [comment]
@ablaom Yes, the `input_scitype` declaration in `metadata_model` could be expanded to include `Count` and `OrderedFactor`.
So my understanding is that they could be read as:
`input=Union{MMI.Table(MMI.Continuous, MMI.Count, MMI.OrderedFactor), AbstractMatrix{MMI.Continuous}}`. 
Would the above be aligned with what you had in mind?

**Comment by ablaom** [comment]
Yes, that's perfect. And this change is made to all models exposed to MLJ. 

Can you please make the change? The other issue is then ready for your review as not further change is required there.

**Comment by jeremiedb** [comment]
Changes to `input_scitype` have been incorporated in https://github.com/Evovest/EvoTrees.jl/pull/160. 
Thanks for taking the time to to revise the new docs!
