### ISSUE TITLE
MLJModelInterface.fit does not accept tables?

### ISSUE THREAD

**Issue by olivierlabayle** [Evovest/EvoTrees.jl#169]
Hello,

Thank you for the work here!

Apologies if this is not the right place for the following question. As I understand it, it seems the `MLJModelInterface.fit` method for `EvoTypes` does not allow for general tables (The `machine` interface works well because it calls the `reformat` function beforehand):

```julia
using EvoTrees
using MLJBase

n = 100
X = MLJBase.table(rand(n, 3))
y = rand(n)

evo = EvoTreeRegressor()
MLJBase.fit(evo, 1, X, y)
```

From the [MLJ doc](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#The-form-of-data-for-fitting-and-predicting) I thought that should be the case or am I understanding it wrong?

**Comment by jeremiedb** [comment]
Effectively,  `fit` expects that data provided has went through the `reformat` step. However,  `MLJBase.fit!` works fine on tabular data, and you can actually start training using that function as well, so it may be all that is needed. 
I'd like to have a dedicated tabular handling within EvoTrees, notably to manage categorical data, but I'm missing time for that!

**Comment by olivierlabayle** [comment]
I understand, thank you both for the clarification! 

Maybe the sentence that would benefit from clarification is the following: "If the core algorithm being wrapped requires data in a different or more specific form, then fit will need to coerce the table into the form desired (and the same coercions applied to X will have to be repeated for Xnew in predict)." 

It is indeed later said that the data front-end is an alternative option but it wasn't obvious that the `MLJModelInterface.fit` would then not be required to respect the "table input contract".

**Comment by ablaom** [comment]
How about, following the cited sentence, we add the new sentence: 

"An exception to this requirement occurs when a data front-end is implemented; see [Implementing a data front-end](@ref) below."

**Comment by olivierlabayle** [comment]
That would be great thank you!

**Comment by jeremiedb** [comment]
I'm assuming this can be closed. Feel fre to reopen otherwise.
