### ISSUE TITLE
Verbosity vs Initial tracking info

### ISSUE THREAD

**Issue by gugatr0n1c** [Evovest/EvoTrees.jl#174]
Hello,

runinng julia 1.8.2, EvoTrees 0.12.2

In fit_evotree - shouldn't be printing "Initial tracking info"  hidden behing "if verbosity > 0 end"?

Cheers
Lubo

![image](https://user-images.githubusercontent.com/17110787/197542730-4c078a43-775d-4cc5-9a36-614df9a7cc9a.png)

**Comment by jeremiedb** [comment]
Absolutely! The fix has been integrated in v0.12.3. Initial metric will now only be printed if verbosity > 0. 
Thanks for bringing this up!
