### ISSUE TITLE
GPU saved model not possible open without CUDA

### ISSUE THREAD

**Issue by gugatr0n1c** [Evovest/EvoTrees.jl#189]
Hello,

not sure if I missed something, but I got error opening model file built with gpu on non-cuda machine.

So, I am using: julia 1.8.2, EvoTrees 0.12.3, WIN10, on both machines.
On one machine I built model with gpu - nvidia card with CUDA.jl and CUDA toolkit.
Model is saved with JLSO package.

Than later I want to open this model on the other machine without CUDA toolkit and I got error:

[warn | JLSO]: Could not find the CUDA driver library. Please make sure you have installed the NVIDIA driver for your GPU.
If you're sure it's installed, look for `nvcuda.dll` in your system and make sure it's discoverable by the linker.
Typically, that involves adding an entry to PATH.

There is of course workaround, not to use gpu.
But would be nice to have what ie Flux.jl have: cpu(model) <--> gpu(model) to "translate" model from "gpu world" to "cpu only world".

Typical usecase is to build model on powefull gpu-have machine, than later for "prediction-phase" use it on regular weaker machine.
Is there something I missed? Can I use model built with gpu on non-cuda machine?

Cheers, Lubo

**Comment by jeremiedb** [comment]
Hello, 

Just like with Flux, it's not advisable to save GPU objects. 
The approach with EvoTrees is similar, it is to convert the model, which is a `EvoTreeGPU` struct into a `EvoTree`, which has all its internals on the CPU: 
```julia
model_cpu = convert(EvoTrees.EvoTree, model_gpu);
```

Then, `model_cpu` can be saved and loaded on another machine without CUDA.

**Comment by gugatr0n1c** [comment]
Hello,

thanx for direction to solve this.
With EvoTrees.EvoTree I get UndefVarError - but I found in the code for saving GPU model convert(EvoTrees.GBTree, model).

This seems to be working.
Thank you
Lubo

**Comment by jeremiedb** [comment]
For clarification, `GBTree` / `GBTreeGPU` is valid up to EvoTrees v0.12. Starting with EvoTrees v0.13, the structs become: `EvoTree` / `EvoTreeGPU`.
