### ISSUE TITLE
ERROR: CURANDError: kernel launch failure (code 201, CURAND_STATUS_LAUNCH_FAILURE)

### ISSUE THREAD

**Issue by MrBenzWorld** [Evovest/EvoTrees.jl#203]
using MLJ
using EvoTrees

EvoTreeRegressor = @load EvoTreeRegressor verbosity=0

model = EvoTreeRegressor ()

ERROR: CURANDError: kernel launch failure (code 201, CURAND_STATUS_LAUNCH_FAILURE)

it is not working on CPU.  Please fix it. 
itis not working on Julia 1.8.4 , EvoTrees v0.14.3

**Comment by jeremiedb** [comment]
Sorry, can't reproduce. Will need greater context to be able to help here.

**Comment by jeremiedb** [comment]
Please try release v0.14.4, it might fix what you encountered.

**Comment by MrBenzWorld** [comment]
Thank you.    v0.14.4 is solved the problem. 
@jeremiedb @ablaom
