### ISSUE TITLE
Feature request: support init_model

### ISSUE THREAD

**Issue by gugatr0n1c** [Evovest/EvoTrees.jl#206]
Hello,

it would be great to support "init_model" for training from existing model.
This feature is supported by lightgbm, xgboost and scikit learn.
It would be great to have here as well.

There is several motivations here:
a] do some specific "callbacks operations" every k-iterations
b] re-train / fine-tune model with some new data in later phase

Thanks for consideration
Lubo

**Comment by jeremiedb** [comment]
I think the required ingredients are already in place for such scenarios where you'd want more granular control over the training loop. Essentially, the idea would be to reuse the implementation of the MLJ fitting logic: https://github.com/Evovest/EvoTrees.jl/blob/7c989bb03863e951ee8ba8233460f18584f45d53/src/MLJ.jl#L1-L13

To synthesize: 
```julia
# initialize a EvoTree model `m` and associated cache.
m, cache = init_evotree(params_evo; x_train, y_train);

# grow a single tree (will update the nrounds count in `cache[:info][:nrounds]`
grow_evotree!(m, cache, params_evo)

# then, assuming the above model `m` has been saved and load back, the ones want to contiue training, a new initialization of can be performed. 
# Resulting initialized model `_m` will be ignored, as we will instead grow the previously trained `m` model.
_m, cache = init_evotree(params_evo; x_train, y_train);

# continue mode ltraining on existing or new data (as specified in previous `init_evotree`.
grow_evotree!(m, cache, params_evo)
```

**Comment by jeremiedb** [comment]
@gugatr0n1c Is the above providing the desired functionality?

**Comment by gugatr0n1c** [comment]
Hi @jeremiedb , this looks exatly what I wrote aboout.. I will try it in detail and report any issues, thanx a lot

**Comment by gugatr0n1c** [comment]
Actually, this can been useful for some other experiments, ie: https://github.com/Evovest/EvoTrees.jl/issues/161, one can use this for some research...
