### ISSUE TITLE
Initialization of rng

### ISSUE THREAD

**Issue by bkamins** [Evovest/EvoTrees.jl#245]
Following my post https://bkamins.github.io/julialang/2023/08/11/evotrees.html

maybe you could consider changing (and related lines)

https://github.com/Evovest/EvoTrees.jl/blob/main/src/models.jl#L37

to something that does not affect task local RNG state?

(this is what https://github.com/Evovest/EvoTrees.jl/blob/main/src/models.jl#L35 for older versions of Julia)

Also - maybe it would be worth to add a comment (as probably many users will not be aware of it) that to get full reproducibility of a model one should pass RNG (and not just a seed). As currently the results of building of a model would depend on Julia version used.

Thank you for developing such a fantastic package.

**Comment by jeremiedb** [comment]
Should be resolved with following section in docs: https://evovest.github.io/EvoTrees.jl/dev/#Reproducibility
As well as the rng now always being MersenneTwister.

**Comment by bkamins** [comment]
Bravo! Top quality. Thank you!
