### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by rikhuijzer** [Evovest/EvoTrees.jl#265]
Is there a way in which I can cite this package?

**Comment by jeremiedb** [comment]
I haven't had a thought about it as it wasn't produced in an academic context, but we sure would appreciate having the EvoTrees cited if used in your work. Are you aware of a recommended way to go about it? I noticed the zenodo DOI tag in packages like ChainRules (https://github.com/JuliaDiff/ChainRules.jl?tab=readme-ov-file), would that work?

**Comment by rikhuijzer** [comment]
Yes Zenodo would work 👍 Preferably within 2 weeks, then I can add it to a current paper before submitting it.

As a side-note, Zenodo is part of the Journal of Open Source Software submission process, so even after adding Zenodo, you can still publish to Journal of Open Source Software.

**Comment by jeremiedb** [comment]
Zenodo's DOI added to README: 
https://zenodo.org/doi/10.5281/zenodo.10569604
Let me know if you need anything else!

**Comment by rikhuijzer** [comment]
Thanks @jeremiedb 

```bibtex
@misc{desgagne2024evotrees,
    title={{EvoTrees.jl}},
    author={Desgagne-Bouchard, J. and Blaom, A. and Qin, A. and Widmann, D. and Lienart, T. and Aluthge, D. and Akavia, R. and Waczak, J. and Ling, J. and Gennatas, S.},
    publisher={CERN},
    year={2024},
    doi={10.5281/zenodo.10569605}
}
```

@ablaom, @amyhxqin, @devmotion, @tlienart, @DilumAluthge, @RoyiAvital, @john-waczak, @Moelf, @egenn this is what I've added as a citation now. Please let me know if I made a mistake.

**Comment by RoyiAvital** [comment]
I guess it should be `Avital R.` instead of `Akavia, R.`.

**Comment by jeremiedb** [comment]
@rikhuijzer Can this issue be closed?
