### ISSUE TITLE
JLBoost.jl similar

### ISSUE THREAD

**Issue by xiaodaigh** [Evovest/EvoTrees.jl#27]
I am making [JLBoost.jl](https://github.com/xiaodaigh/JLBoost.jl) which is similar in many ways

**Comment by jeremiedb** [comment]
Are you seeing areas for collaboration?

**Comment by xiaodaigh** [comment]
Yeah, like defining an `AbstractGradientBoostingTree`? When the time is right, and make consistent the API?

I see you that you implemented the histogram method while I have implemented the exact method. The underlying algorithms should be the same. I also got CuArrays working. 

Happy to close this issue now that you are aware of JLBoost. Happy to discuss any collaboration if needed.
