### ISSUE TITLE
Bump [compat] MLJModelInterface="^0.1, ^0.2"

### ISSUE THREAD

**Issue by ablaom** [Evovest/EvoTrees.jl#45]
Here the changes since 0.1.8, which I doubt break anything in EvoTrees:

- [x] Bring in `is_same_except` and similar gizmos from MLJBase;  see https://github.com/alan-turing-institute/MLJBase.jl/issues/178

- [x] Let all models share same traits (#19, https://github.com/alan-turing-institute/MLJBase.jl/issues/163)

- [x] Add `save` and `restore` stubs for serialisation

If you wanted to make use of `is_same_except` you would need the more restrictive 

```julia
[compat] MLJModelInterface="^0.2"
```

**Comment by jeremiedb** [comment]
Fixed with PR #46 
No use of `is_same_except` at the moment so compat is for 0.1 and 0.2 for now.
