### ISSUE TITLE
Raise lower bound: [compat] MLJModelInterface = "^0.3"

### ISSUE THREAD

**Issue by ablaom** [Evovest/EvoTrees.jl#49]
This will allow your classifier to buy into [this](https://github.com/alan-turing-institute/MLJBase.jl/pull/327) performance improvement. Apart from the [compat] update, the only other step should be to replace the following line

https://github.com/Evovest/EvoTrees.jl/blob/4235aa2548ce93a60ebe6df18f9909fa856ee71a/src/MLJ.jl#L46

with

```julia
    return MLJModelInterface.UnivariateFinite(fitresult.levels, pred)
```
which returns an instance of an *abstract* vector of eltype <: UnivariateFinite instead of a vanilla vector of the same eltype. You should not need to change any tests - this object should have all the same behaviour as the old one.

FYI: I am releasing today an MLJModels update which will also have MLJModelInterface 0.3 as a lower bound (and performance buy-in for all the classifiers with implementations there). 

Let me know if you have questions.

**Comment by jeremiedb** [comment]
@ablaom Thanks for the heads up. 

However, regarding the UnivariateFinite, I'm still having struggles. 
Using the `MLJModelInterface.UnivariateFinite(fitresult.levels, pred)` resulted in an error regarding the format not being of either CategoricalString or CategoricalValue. 
Also, I couldn't even run a simple example in the UnivariateFinite example: 

```julia
v = categorical([:x, :x, :y, :x, :z])
UnivariateFinite(classes(v), [0.2, 0.3, 0.5])

MethodError: no method matching classes(::FullInterface, ::CategoricalArray{Symbol,1,UInt32,Symbol,CategoricalValue{Symbol,UInt32},Union{}})
Closest candidates are:
  classes(!Matched::LightInterface, ::Any) at C:\Users\Jeremie\.julia\packages\MLJModelInterface\DJKg2\src\data_utils.jl:124
  classes(::FullInterface, !Matched::CategoricalPool) at C:\Users\Jeremie\.julia\packages\MLJBase\O5b6j\src\interface\data_utils.jl:25
  classes(::FullInterface, !Matched::Union{CategoricalValue{String,R} where R, CategoricalValue}) at C:\Users\Jeremie\.julia\packages\MLJBase\O5b6j\src\interface\data_utils.jl:30
 ...
```

This was using the latest MLJModelInterface, MLJBase and CategoricalArrays releases: 

```
(EvoTrees) pkg> st
Project EvoTrees v0.4.7
Status `D:\Evovest\EvoTrees.jl\Project.toml`
  [324d7699] CategoricalArrays v0.8.1
  [31c24e10] Distributions v0.23.4
  [a7f614a8] MLJBase v0.13.10
  [e80e1ace] MLJModelInterface v0.3.0
  [90137ffa] StaticArrays v0.12.3
  [2913bbd2] StatsBase v0.33.0
  [9a3f8284] Random
  [10745b16] Statistics
```

Is it possible that there are some components that are out of sync?

**Comment by ablaom** [comment]
That's weird. I am unable to reproduce your error:

```julia
(kkjj) pkg> st
    Status `~/.julia/environments/kkjj/Project.toml`
  [324d7699] CategoricalArrays v0.8.1
  [a7f614a8] MLJBase v0.13.10
  [e80e1ace] MLJModelInterface v0.3.0
  [90137ffa] StaticArrays v0.12.3
  [9a3f8284] Random 
  [10745b16] Statistics 

julia> using MLJBase

julia> v = categorical([:x, :x, :y, :x, :z])
5-element CategoricalArrays.CategoricalArray{Symbol,1,UInt32}:
 :x
 :x
 :y
 :x
 :z

julia> UnivariateFinite(classes(v), [0.2, 0.3, 0.5])
UnivariateFinite{Multiclass{3}}(x=>0.2, y=>0.3, z=>0.5)
```

> regarding the format not being of either CategoricalString or CategoricalValue.

This sounds like old code. There should no longer be any signs of `CategoricalString` which was deprecated in CategoricalArrays 0.8 . Can you give me the full stack trace for that error please?

**Comment by ablaom** [comment]
```
julia> versioninfo()
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PATH = /Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
```

**Comment by jeremiedb** [comment]
It seems the issue was stemming from a failure on my general registry, fixed with the following: https://stackoverflow.com/questions/60755847/general-registry-failed-to-update-in-julia/

The new `UnivariateFinite` now works fine. I'm releasing the update version. Sorry for the false alert!
