### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by xgdgsc** [Evovest/EvoTrees.jl#57]
How do you deploy? Consider adding save/load functions? Or be able to export to some format of other packages like lightgbm/xgboost to leverage the package [dmlc/treelite: model compiler for decision tree ensembles](https://github.com/dmlc/treelite)?

**Comment by jeremiedb** [comment]
Current, the approach for saving/loading would be using BSON: 

```julia
using BSON: @save, @load
@save "model_L1.bson" model
@load "model_L1.bson" model
```

I hadn't consider integrating at the moment. Would that be a useful feature to you?

**Comment by xgdgsc** [comment]
Yes, though not with a high priority. Some applications may require c library integration. And I' d be curious how would julia compare with the code generated with treelite.

**Comment by jeremiedb** [comment]
I just updated the benchmarks to include inference and EvoTrees appears to perform surprisingly well compared to XGBoost: 

### Inference:

| Dimensions   / Algo | XGBoost Hist | EvoTrees | EvoTrees GPU |
|---------------------|:------------:|:--------:|:------------:|
| 100K x 100          |    0.177s    |  0.029s  |    0.035s    |
| 500K x 100          |    0.861s    |  0.191s  |    0.214s    |
| 1M x 100            |     1.67s    |  0.400s  |    0.469s    |
| 5M x 100            |     8.51s    |   2.14s  |     2.43s    |
