### ISSUE TITLE
Crash occured when fitting

### ISSUE THREAD

**Issue by SimonCrouzet** [Evovest/EvoTrees.jl#64]
Hi and thanks for this package!

I noticed a bug when I was running the following code. I have a black screen during 5min, then I have the attached screen. We tried the same code under a Linux distribution (also using VS Code) and everything went fine, so I guess it's a W10-linked issue! Please feel free to ask if you need more info

[vs_crash](https://user-images.githubusercontent.com/44019276/99917533-30b82300-2d11-11eb-938d-9a0edadc1c03.JPG)

```## EvoTrees
using EvoTrees
println(stdout, "Tuning EvoTrees...")
MLJ.@load EvoTreeClassifier
evotree_model_base = EvoTreeClassifier(nrounds=100)

# Step 1 of our tuning
evotree_step1 = [  range(evotree_model_base, :max_depth; lower=3, upper=10, unit=1),
                            range(evotree_model_base, :min_weight; lower=1, upper=6, unit=1)   ]
tuned_evotree_model = TunedModel(model=evotree_model_base,
                                            tuning=rnd_search,
                                            resampling=StrCV,
                                            repeats=3,
                                            # n=5,
                                            range=evotree_step1,
                                            measure=probabilistic_accuracy,
                                            acceleration=CPUThreads()
                                            )
tuned_evotree = machine(tuned_evotree_model, X, y)

println(stdout, "EvoTrees: Step 1")
@time fit!(tuned_evotree, verbosity=1, rows=train_indexes)

savefig(plot(tuned_evotree), "HeatMap_EvoTrees_Step1.png")
evotree_model = fitted_params(tuned_evotree).best_model

**Comment by jeremiedb** [comment]
Sorry about the delay, I missed the notification :/

BTW, it would be preferable if you could provide a minimal reproducible example so it can help the debugging. 
That being said, from a test case, I also hit a crash during the fitting process. 

```julia
using EvoTrees
using MLJModelInterface
using MLJBase
using StatsBase: sample, mean, quantile
using MLJ
using Tables

features = rand(10_000, 100)
# features = rand(100, 10)
X = features
Y = rand(size(X, 1))

X_tbl = Tables.table(X);
X_tbl = Tables.rowtable(X);
println(stdout, "Tuning EvoTrees...")
MLJ.@load EvoTreeClassifier
evotree_model_base = EvoTreeRegressor(nrounds=100)

# Step 1 of our tuning
evotree_step1 = [   range(evotree_model_base, :max_depth; lower=3, upper=5, unit=1),
                    range(evotree_model_base, :min_weight; lower=10, upper=20, unit=1)]

tuned_evotree_model = TunedModel(model=evotree_model_base,
                                            tuning=RandomSearch(),
                                            resampling=CV(nfolds=6),
                                            range=evotree_step1,
                                            measure=rms,
                                            acceleration=CPUThreads()
                                            )

tuned_evotree = machine(tuned_evotree_model, X_tbl, Y_train);

println(stdout, "EvoTrees: Step 1")
fit!(tuned_evotree, verbosity=1) # crashes here
```  

Have you tried tuning your model directly with the EvoTrees functionality? This is what I've been so far using in my work, and I haven't encountered such issues so far. 

I'm currently taking a look at some new functionalities of MLJ, so should be able to take a look at this issue in the upcoming days (no result guaranteed :P )

**Comment by jeremiedb** [comment]
Actually, may I ask you more detail about your hardware? Would it be a recent laptop with AMD cpus by any chance? 
I've actually experienced weird failures with a new wnidows laptop with Ryzen 7 cpus on Win10. No issue on another Intel cpu with Win10 nor a AMD Threadripper on Linux with same package versions. 

I opened a thread here but haven't found the a root cause: https://discourse.julialang.org/t/multi-thread-issue-on-windows-10-home-or-libuv/49089/5

In my case, the very puzzling solution is to shut down then, power on the laptop and... it works! I actually just tried it with the above script and it ran correctly.

**Comment by SimonCrouzet** [comment]
No worries, thanks for the answer! I'm a little bit late as well, but here is some informations:

I tried again to run a training, with a prebuild dataset (from RDatasets) this time, and I didn't encounter any crash. I think it might be linked to how RAM is handled under W10 (I feel like Julia is still not managing perfectly its garbage collector, even if v1.5 brought a lot of progress).

About my hardware, I have an Intel i5-7300HQ with 8Go of RAM.

I'll try to run again an EvoTree fitting with my own data after several hours of other scripts (which should use the RAM), I'll let you know about the results!

**Comment by jeremiedb** [comment]
Just wondering if you had the occasion to perform new runs on Windows under Julia 1.6 and if issues were still present?

**Comment by jeremiedb** [comment]
Thanks for the feedback. 
It appears like the dependency for `MLJModelInterface.jl` should have been restricted to v1+. 
Could you make a test following an update of MLJModelInterface 1.0?

**Comment by ablaom** [comment]
FYI MLJModelInterface 1.0 is identical to MLJModelInterface 0.4.1.

**Comment by ablaom** [comment]
@jeremiedb If I explicitly include MLJModelInterface in my environment, as in your crashing code snippet, then MLJ gets pushed down to an ancient version (probably because MLJ has not upped it's MLJModelInterface compat yet - although the order I build my env may matter) and will not even compile. 

However, if I drop MLJModelInterface and MLJBase (which you do not use in your code snippet) then I am unable to reproduce the crash:

```julia
julia> fit!(tuned_evotree, verbosity=1) # crashes here
[ Info: Training Machine{DeterministicTunedModel{RandomSearch,…},…} @601.
[ Info: Attempting to evaluate 10 models.
Evaluating over 10 metamodels: 100%[=========================] Time: 0:00:41
Machine{DeterministicTunedModel{RandomSearch,…},…} @601 trained 1 time; caches data
  args: 
    1:  Source @376 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @350 ⏎ `AbstractVector{Continuous}`
```

Can you do `Pkg.status()` please?

**Comment by jeremiedb** [comment]
Using  `[add582a8] MLJ v0.16.1` and ` EvoTrees v0.7.4` I no longer have the crash either. 
Not sure at what point the issue got fixed, but it looks like using up to date versions of MLJ and EvoTrees should work fine.
