### ISSUE TITLE
Unable to reproduce plot from Readme tutorial

### ISSUE THREAD

**Issue by casasgomezuribarri** [Evovest/EvoTrees.jl#67]
Hi and thanks for this package :)

I was trying to plot my decision tree using the `plot(model, n)` method outlined at the end of the Readme tutorial, but got the following error:

> ERROR: Cannot convert EvoTrees.GBTree{1,Float32,Int64} to series data for plotting. 

I came back to this repo and copy-pasted all the code from the Readme file, and still got the same error, so it should be fairly easy to replicate.

I am using **EvoTrees v0.5.3**,  **Plots v1.6.12** and **Julia v1.4.2** on **VSCode v1.52.1**.

**Comment by casasgomezuribarri** [comment]
This issue was resolved after I restarted my laptop and tried again, both for the readme tutorial and my personal code.

**Comment by jeremiedb** [comment]
Glad it ended up working. Thanks for your interest in the library!
