### ISSUE TITLE
method error with importance()

### ISSUE THREAD

**Issue by casasgomezuribarri** [Evovest/EvoTrees.jl#73]
I have two models stacked, one of each is an ensemble of `EvoTreeClassifier` models, and I am working with `MLJ`.

I want to know the feature importance according to the ensemble of `EvoTreeClassifier`s, but I am getting the following error:

```julia
julia> f = fitted_params(tuned_stack)
julia> features_gain = importance(f.best_fitted_params.model2.fitresult, wvn_table)
ERROR: MethodError: no method matching importance(::MLJ.WrappedEnsemble{EvoTrees.GBTree{2,Float32,Int64},EvoTreeClassifier{Float32,EvoTrees.Softmax,Int64}}, ::Array{Any,1})
Closest candidates are:
  importance(::EvoTrees.GBTree, ::AbstractArray{T,1} where T) 
at C:\Users\ivica\.julia\packages\EvoTrees\9NdxH\src\importance.jl:12
```

For clarity, the output of `f.best_fitted_params.model2.fitresult` is 
```julia
julia> f.best_fitted_params.model2.fitresult
WrappedEnsemble{GBTree{,…},…} @546
```

I understand that I have to feed an object of the type `::EvoTrees.GBTree` to the `importance()` function... How could I do so when my model is an ensemble of `::EvoTrees.GBTree`s?

**Comment by ablaom** [comment]
For a start, it looks to me that the MLJ wrap of `EvoTreeClassifier` does not expose feature importances. Normally in MLJ a feature importance is exposed in the fitted machine's report. Here's an example:

```julia
julia> xgb = (@iload XGBoostClassifier)()
julia> mach2 = machine(xgb, X, y) |> fit!
julia> report(mach2)
(feature_importances = 4-element Vector{XGBoost.FeatureImportance}:
Gain      Coverage  Frequency  Feature
0.6703    0.5138    0.2845     petal_length
0.3118    0.2902    0.3054     petal_width
0.0108    0.0863    0.1883     sepal_width
0.0071    0.1097    0.2218     sepal_length
,)
```

When I do this for EvoTreeClassifier, the report is empty.

You could post an issue requesting that feature importances be exposed in the MLJ wrap. Copy me in and I may take a look at it.

**Comment by ablaom** [comment]
A second issue is that currently there is no interface point for accessing individual "atomic reports" in an ensemble. Again, feel free to post an issue at MLJ. 

You can however access reports for models wrapped as TunedModel.

**Comment by casasgomezuribarri** [comment]
Thanks! Does that mean that even if MLJ could report feature importance of `EvoTreeClassifier`s, them being wrapped in an `EnsembleModel` would prevent me from accessing that information?

**Comment by ablaom** [comment]
Yes, there is no way. Currently, the EnsembleModel wrapper only accumulates the learned parameters for each atomic model (`fitresult` in the code) but not the reports, which would contain the individual feature importances. 

I've opened an issue: https://github.com/alan-turing-institute/MLJ.jl/issues/746 . PR welcome.

**Comment by casasgomezuribarri** [comment]
I'll close this issue since it has been broken down into two other issues that address the problem more concisely :)
